### ISSUE TITLE
Textblock in the javacode makes the maven build fail

### ISSUE THREAD

**Issue by kajh** [revelc/impsort-maven-plugin#45] opened 2021-05-10 12:03 UTC
**Describe the bug**
If we have a class like the following with a textblock
```
import org.junit.jupiter.api.Test;

public class TextBlockTestCase {

    @Test
    public void hello() {
        String s = """
                hello world
                """;
    }
}
```
and run ```mvn process-sources``` it fails with
```
[ERROR] Failed to execute goal net.revelc.code:impsort-maven-plugin:1.6.0:sort (sort-imports) on project nettskjema-api: Error reading file /MyPath/TextBlockTestCase.java: file: /MyPath/TextBlockTestCase.java; reason: the Java file contained parse errors -> [Help 1]
```

**Versions (OS, Maven, Java, and others, as appropriate):**
 - impsort-maven-plugin 1.6.0

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Create a class with a textblock like the one described above
2. Run ```mvn process-sources```

**Expected behavior**
No errors

**Comment by ctubbsii** [comment] 2021-05-10 19:25
I created a test case for this, and for #44, and both features seemed to work fine if I set the compliance level to `13_PREVIEW`, `14_PREVIEW`, or `15` or `16`, using the `<compliance>` option of this plugin. By default, this option is set to the value of `maven.compiler.release`. So, you should ensure that is set on your project to `16` if that is the version you are using.

What is your configuration?

**Comment by ctubbsii** [comment] 2021-05-10 19:50
I think this is user configuration error, since I can't reproduce it. Closing it for now, but can re-open if it can be reproduced.

**Closed by ctubbsii** 2021-05-10 19:50 UTC
Labels: cannot reproduce

**Comment by kajh** [comment] 2021-05-11 05:26
Hi, thank you for looking into this issue! Sorry for not providing my config for impsort-maven-plugin in my bugreport! I can confirm that textblocks works fine on version impsort-maven-plugin 1.6.0 when I add ```<compliance>16</compliance>``` and when adding that I can not reproduce this issue.
