### ISSUE TITLE
"Parse error" on java 16 record

### ISSUE THREAD

**Issue by kajh** [revelc/impsort-maven-plugin#44] opened 2021-05-10 11:12 UTC
**Describe the bug**
We get the following error when we have a java 16 record like
```
public record MyDTO(String name) {
}
```
we get the folloing stacktrace:
```
(line 3,col 1) Parse error. Found  "record" <IDENTIFIER>, expected one of  ";" "@" "class" "enum" "interface" "module" "open"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:12827)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:12673)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:170)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.parse(JavaParser.java:306)
  net.revelc.code.impsort.ImpSort.parseFile(ImpSort.java:128)
  net.revelc.code.impsort.maven.plugin.AbstractImpSortMojo.lambda$execute$3(AbstractImpSortMojo.java:282)
  java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
  java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
  java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
  java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
  java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
  java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
  java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
  java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
  java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
  java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
  java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
  java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
  java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
  java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
  java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
  java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Versions (OS, Maven, Java, and others, as appropriate):**
 - impsort-maven-plugin 1.6.0

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Create a record like shown above
2. add the plugin to pom.xml like shown on https://code.revelc.net/impsort-maven-plugin/
3. Run ```mvn process-sources```

**Expected behavior**
No errors on records.

**Comment by ctubbsii** [comment] 2021-05-10 19:47
I can't reproduce this, even with the existing 3.19.0 javaparser release. See my comment on https://github.com/revelc/impsort-maven-plugin/issues/44#issuecomment-837194575 ; this should work if you set `maven.compiler.release` to 16 in your project, or override it in the plugin configuration with `<compliance>13_PREVIEW</compliance>` (or `14_PREVIEW`, `15`, or `16`, whichever is most appropriate for your project).

**Comment by ctubbsii** [comment] 2021-05-10 19:50
I think this is user configuration error, since I can't reproduce it. Closing it for now, but can re-open if it can be reproduced.

**Comment by ctubbsii** [comment] 2021-05-11 08:29
Thanks for following up with the example project, @kajh . I can verify the problem still occurs. I modified my test case slightly and can reproduce the problem. It seems to be that there is no parse error if the record is an inner-class, but there is a parse error if it's not an inner-class. I'm not sure why this is the case. I can try to look into this more.

**Comment by ctubbsii** [comment] 2021-05-12 15:33
It looks like the parser is incorrectly parsing the inner class and assuming it is a return type of a method, rather than a reserved keyword for a special class definition. That's why it worked for inner classes. It turns out this wasn't properly supported by javaparser until 3.22, which was released on May 10, the same day this issue was opened here. I will bump to that dependency version, which should fix this issue.

**Closed** 2021-05-12 15:38 UTC
Labels: bug

**Comment by ctubbsii** [comment] 2021-05-12 16:04
This should be fixed in release 1.6.1, which I pushed to Maven Central today. Let me know if you still have issues with this, and thanks for reporting the problem!

**Comment by famod** [comment] 2021-05-13 18:44
It seems `javaparser` is now a bit overzealous in what it considers a `record`: https://github.com/quarkusio/quarkus/pull/17190#issuecomment-840111089
I suppose I need to report it upstream?

**Comment by ctubbsii** [comment] 2021-05-13 19:00
> It seems `javaparser` is now a bit overzealous in what it considers a `record`: [quarkusio/quarkus#17190 (comment)](https://github.com/quarkusio/quarkus/pull/17190#issuecomment-840111089)
> I suppose I need to report that issue upstream?

Yes, definitely report it upstream. If the parser is misinterpreting a variable named "record" as a keyword, there is nothing we can do here in this plugin, but update to the new release when it is fixed upstream. If you have a minimal file that can reproduce this, please open a new issue or PR, and we can add it as a test case to verify the bug and to verify any fix that might come from upstream.

**Comment by kajh** [comment] 2021-05-13 19:14
@ctubbsii Thanks for fixing the problems with records. With 1.6.1 I can't reproduce this issue.

**Comment by famod** [comment] 2021-05-13 20:53
> 
> 
> > It seems `javaparser` is now a bit overzealous in what it considers a `record`: [quarkusio/quarkus#17190 (comment)](https://github.com/quarkusio/quarkus/pull/17190#issuecomment-840111089)
> > I suppose I need to report that issue upstream?
> 
> Yes, definitely report it upstream. If the parser is misinterpreting a variable named "record" as a keyword, there is nothing we can do here in this plugin, but update to the new release when it is fixed upstream. If you have a minimal file that can reproduce this, please open a new issue or PR, and we can add it as a test case to verify the bug and to verify any fix that might come from upstream.

Please see https://github.com/javaparser/javaparser/issues/3261

**Comment by vedantivyawahare-tomtom** [comment] 2024-03-14 09:54
Hey, I'm using import-maven-plugin with latest version(1.9.0). I'm still getting Caused by: org.apache.maven.plugin.MojoFailureException: Error reading file C:\Users\vyawahav\Workspace\genesis-addr-apt-delta-consumer\common-utils\src\main\java\com\tomtom\address\dt
o\Zone.java
using record in zone.java
