### ISSUE TITLE
Parsing error when java file contains variable named `permits`

### ISSUE THREAD

**Issue by NathanEckert** [revelc/impsort-maven-plugin#78] opened 2023-10-27 09:02 UTC
**Describe the bug**

After upgrading from version `1.8.0` to `1.9.0`, when a variable in a file is named `permits`, the plugin execution fails on a parsing error.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: `1.9.0`

```
mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /home/nec/.sdkman/candidates/maven/current
Java version: 11.0.20, vendor: Eclipse Adoptium, runtime: /home/nec/.sdkman/candidates/java/11.0.20-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.2.0-35-generic", arch: "amd64", family: "unix"
```

**To Reproduce**
1. Create a file:

```java
package mypackage.mypackage

import java.util.concurrent.atomic.AtomicInteger;

public class TestPermitKeyword {

	void testPermitKeyWord() {
		final AtomicInteger permits = new AtomicInteger(0);
	}

}
```

2. Run command :  `mvn -DskipTests -Dcheckstyle.skip impsort:sort@sort-imports`
3. Error is:

```
[ERROR] Failed to execute goal net.revelc.code:impsort-maven-plugin:1.9.0:sort (sort-imports) on project myProject: Error reading file /home/path/to/myProject/path/to/file/TestPermitKeyword.java: file: /home/path/to/myProject/path/to/file/TestPermitKeyword.java; reason: the Java file contained parse errors
```
4. Workaround: rename variable `permits` to `nPermits`

**Expected behavior**
No parse error

**Comment by ctubbsii** [comment] 2023-11-13 19:12
I believe this is a duplicate of #72 and will be fixed in 1.10.

**Closed** 2023-11-20 23:26 UTC
Labels: bug, duplicate
