### ISSUE TITLE
A required class was missing while executing net.revelc.code:impsort-maven-plugin:1.5.0:sort: org/codehaus/plexus/util/DirectoryScanner

### ISSUE THREAD

**Issue by leesonwei** [revelc/impsort-maven-plugin#69] opened 2023-02-21 05:53 UTC
**Describe the bug**
[INFO] --- impsort:1.5.0:sort (default) @ process-usertasks-quarkus-with-console ---
[INFO] Using compiler compliance level: JAVA_11
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.941 s
[INFO] Finished at: 2023-02-21T14:12:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.revelc.code:impsort-maven-plugin:1.5.0:sort (default) on project process-usertasks-quarkus-with-console: Execution default of goal net.revelc.code:impsort-maven-plugin:1.5.0:sort failed: A required class was missing while executing net.revelc.code:impsort-maven-plugin:1.5.0:sort: org/codehaus/plexus/util/DirectoryScanner
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.revelc.code:impsort-maven-plugin:1.5.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/root/.m2/repository/net/revelc/code/impsort-maven-plugin/1.5.0/impsort-maven-plugin-1.5.0.jar
[ERROR] urls[1] = file:/root/.m2/repository/com/github/javaparser/javaparser-core/3.18.0/javaparser-core-3.18.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.kie.kogito.examples:process-usertasks-quarkus-with-console:1.34.0.Final, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : org.codehaus.plexus.util.DirectoryScanner
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0]
 - OS: [e.g. CentOS 7.5]
 - Others: 

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hazendaz** [comment] 2023-02-21 12:05
Without more details I'm guessing here.  You likely are using maven 3.9.0 or 4.0.0.alpha releases.  This requires you provide plexus utility or use latest impsort plugin.  So please use latest impsort plugin and let us know if that solves your issue.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ctubbsii** [comment] 2023-02-24 15:00
Closing as duplicate of #64, which is fixed by #65 in 1.8.0. Please reopen or comment here with more details if this is a separate issue.

**Closed by ctubbsii** 2023-02-24 15:00 UTC
Labels: bug, duplicate
