### ISSUE TITLE
Error with Jdk 21 Pattern Matching for switch

### ISSUE THREAD

**Issue by amkac** [revelc/impsort-maven-plugin#84] opened 2023-12-18 12:09 UTC
**Describe the bug**

I am getting an issue with the impsort plugin when running the sort goal with JDK 21. The plugin appears to be incompatible with the new feature, pattern matching for switch I am receiving a parsing error during execution.
My implementation is the following 
```
    private String getMessage(Object obj) {
        return switch (obj) {
            case Integer i -> String.format("int type %d", i);
            case Long l -> String.format("long type %d", l);
            case Double d -> String.format("double type %f", d);
            case String s -> String.format("String type %s", s);
            default -> obj.toString();
        };
    }
```

**Versions (OS, Maven, Java, and others, as appropriate):**
 - JAVA 21
 - Maven 3.9.6
 - impsort 1.9.0

**To Reproduce**
1. implement Pattern Matching for switch in your code like my example above
2. run mvn impsort:check

**Exception**
 The exception 
`(line 52,col 18) Parse error. Found  "i" <IDENTIFIER>, expected one of  "!=" "%" "&" "&&" "(" "*" "+" "," "-" "->" "/" ":" "<" "<=" "==" ">" ">=" "?" "^" "instanceof" "|" "||"
Problem stacktrace :
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:13933)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:13778)
  com.github.javaparser.GeneratedJavaParser.SwitchEntry(GeneratedJavaParser.java:6369)
  com.github.javaparser.GeneratedJavaParser.SwitchExpression(GeneratedJavaParser.java:6216)
  com.github.javaparser.GeneratedJavaParser.UnaryExpressionNotPlusMinus(GeneratedJavaParser.java:4494)
  com.github.javaparser.GeneratedJavaParser.UnaryExpression(GeneratedJavaParser.java:4363)
  com.github.javaparser.GeneratedJavaParser.MultiplicativeExpression(GeneratedJavaParser.java:4226)
  com.github.javaparser.GeneratedJavaParser.AdditiveExpression(GeneratedJavaParser.java:4178)
  com.github.javaparser.GeneratedJavaParser.ShiftExpression(GeneratedJavaParser.java:4133)
  com.github.javaparser.GeneratedJavaParser.RelationalExpression(GeneratedJavaParser.java:4073)
  com.github.javaparser.GeneratedJavaParser.InstanceOfExpression(GeneratedJavaParser.java:3992)
  com.github.javaparser.GeneratedJavaParser.EqualityExpression(GeneratedJavaParser.java:3922)
  com.github.javaparser.GeneratedJavaParser.AndExpression(GeneratedJavaParser.java:3877)
  com.github.javaparser.GeneratedJavaParser.ExclusiveOrExpression(GeneratedJavaParser.java:3837)
  com.github.javaparser.GeneratedJavaParser.InclusiveOrExpression(GeneratedJavaParser.java:3797)
  com.github.javaparser.GeneratedJavaParser.ConditionalAndExpression(GeneratedJavaParser.java:3757)
  com.github.javaparser.GeneratedJavaParser.ConditionalOrExpression(GeneratedJavaParser.java:3712)
  com.github.javaparser.GeneratedJavaParser.ConditionalExpression(GeneratedJavaParser.java:3680)
  com.github.javaparser.GeneratedJavaParser.Expression(GeneratedJavaParser.java:3493)
  com.github.javaparser.GeneratedJavaParser.ReturnStatement(GeneratedJavaParser.java:7024)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:5645)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:5865)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:2773)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:5744)
  com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:2170)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:1771)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:1275)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:538)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:156)
  com.github.javaparser.JavaParser.parse(JavaParser.java:125)
  com.github.javaparser.JavaParser.parse(JavaParser.java:305)
  net.revelc.code.impsort.ImpSort.parseFile(ImpSort.java:129)
  net.revelc.code.impsort.maven.plugin.AbstractImpSortMojo.lambda$execute$3(AbstractImpSortMojo.java:287)
  java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
  java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
  java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
  java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
  java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
  java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
  java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
  java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
  java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
  java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
  java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
  java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
  java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667)
  java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
  java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
  java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
  net.revelc.code.impsort.maven.plugin.AbstractImpSortMojo.execute(AbstractImpSortMojo.java:316)
  org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
  org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
  org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
  org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
  org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
  org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
  org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
  org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
  org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
  org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
  org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
  org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
  org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
  org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
  org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
  org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
  org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  java.base/java.lang.reflect.Method.invoke(Method.java:580)
  org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
  org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
  org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
  org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
(line 52,col 62) Parse error. Found "case", expected "}"
Problem stacktrace :
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:13933)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:13778)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:5745)
  com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:2170)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:1771)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:1275)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:538)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:156)
  com.github.javaparser.JavaParser.parse(JavaParser.java:125)
  com.github.javaparser.JavaParser.parse(JavaParser.java:305)
  net.revelc.code.impsort.ImpSort.parseFile(ImpSort.java:129)
  net.revelc.code.impsort.maven.plugin.AbstractImpSortMojo.lambda$execute$3(AbstractImpSortMojo.java:287)`

**Comment by ctubbsii** [comment] 2023-12-19 07:44
JDK 18+ is known to be broken at the moment, pending upstream javaparser fixes. This is a duplicate of #79

**Closed by ctubbsii** 2023-12-19 07:44 UTC
Labels: bug, duplicate
